sudo: false

language: node_js

node_js:
  - '10.13'

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: never

script:
 - npm run compile
 - npm run test
